---
# Related to user
admin_user: "{{ admin_user }}"
admin_user_group: admin

# Profile
# --------
# profile_paths, earlier items override later ones
profile_paths: [$HOME/.local/bin, /opt/homebrew/bin]
profile_group: "{{ admin_user_group }}"
profile_xdg_include: true
profile_ls_colors: cxexfxdxBxEhebAbAgAcAd
profile_envs:
  - {name: CARGO_HOME, value: $XDG_DATA_HOME/cargo}
profile_custom_entries:
  - "{{ '#' }} Secrets"
  - "export EMAIL='{{ admin_email }}'"

# Fonts
# --------
fonts_to_user: true
fonts_to_get:
  # NOTE: Test pattern for role fonts
  # - pattern: blah*
  - file_pattern: Iosevka*
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Iosevka.zip
  - file_pattern: BigBlue*
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/BigBlueTerminal.zip
  - file_pattern: Fira*
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip
  - file_pattern: Sauce*
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/SourceCodePro.zip

# Homebrew
# --------
homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_casks:
  - aldente
  - github
  - steam
  - visual-studio-code
  # - iterm2-beta  # TODO: Once stable reaches v3.5, switch to just iterm2
  # - mac-mouse-fix  # TODO: Broken till v3 stable releases (currently dl'd)

homebrew_packages:
  - age
  - ansible
  - ansible-lint
  - git
  - jq
  - zstd

# MAS (Mac App Store)
# -------------------
mas_installed_apps:
  - {id: 1432731683, name: 'Adblock Plus for Safari ABP'}
  - {id: 1606897889, name: 'Consent-O-Matic'}
  - {id: 1452453066, name: 'Hidden Bar'}
  - {id: 1463298887, name: 'Userscripts'}
mas_uninstalled_apps:
  - {id: 682658836, name: 'GarageBand'}
  - {id: 408981434, name: "iMovie"}
  - {id: 409203825, name: "Numbers"}
  - {id: 409201541, name: "Pages"}
  - {id: 1482490089, name: 'Tampermonkey'}

# Mac Defaults
# ------------
# TODO: Move some of these into defaults of role
mac_defaults_caps_lock_esc: true
mac_defaults_key_repeat_time: 2
mac_defaults_init_key_repeat_time: 8
mac_defaults_keyboard_vscode_key_hold_enabled: false
mac_defaults_key_hold_enabled: true
mac_defaults_keyboard_automatic_spelling_correct: false
mac_defaults_keyboard_auto_quote_subst: false
mac_defaults_keyboard_auto_dash_subst: false
mac_defaults_spotlight_shown: 0  # 0 = hidden, 1 = visible
