---
# Related to user
# admin_user: "{{ admin_user }}"
admin_user_group: admin

# Shell Dotfiles
# --------------
# Profile
# profile_paths, earlier items override later ones
profile_paths: [$HOME/.local/bin, $HOME/.local/share/pyenv/bin, /opt/homebrew/bin]

# Userdirs
userdirs_custom_dirs: [~/.local, ~/.local/bin, ~/.local/share, ~/.config, ~/.cache, ~/.cache/run]

# ZSH
zsh_default_shell: true
zsh_parent_dir: /Users/{{ admin_user }}/.config
zsh_git_repo: 'git@github.com:marcus-grant/dots-zsh.git'
zsh_extra_packages: [fd, fzf, ripgrep, starship]

# Git
git_extra_packages: [gh, gitui]

# Dev
# ---
# PyEnv
pyenv_versions: ['3.11.2', '3.12.0']

# PIP
pip_sys_extra: [pip-completion, pip-tools]


# Ops
# ---
# Restic

# Fonts
# --------
fonts_to_user: true
fonts_base_url: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0
fonts_to_get:
  # NOTE: Test pattern for role fonts
  # - {pattern: blah*, url: https://example.com/fonts/blah.zip}
  - {file_pattern: Iosevka*, url: "{{ fonts_base_url }}/Iosevka.zip"}
  - {file_pattern: BigBlue*, url: "{{ fonts_base_url }}/BigBlueTerminal.zip"}
  - {file_pattern: Fira*, url: "{{ fonts_base_url }}/FiraCode.zip"}
  - {file_pattern: Sauce*, url: "{{ fonts_base_url }}/SourceCodePro.zip"}

# Homebrew
# --------
homebrew_taps: []  # removed because default taps cause problems

homebrew_casks:
  - aldente
  - github
  - rancher
  - spotify
  - steam
  - visual-studio-code
  # - iterm2-beta  # TODO: Once stable reaches v3.5, switch to just iterm2
  # - mac-mouse-fix  # TODO: Broken till v3 stable releases (currently dl'd)

homebrew_packages:
  - age
  - ansible
  - ansible-lint
  - jq
  - zstd

# MAS (Mac App Store)
# -------------------
mas_installed_apps:
  - {id: 1432731683, name: 'Adblock Plus for Safari ABP'}
  - {id: 1606897889, name: 'Consent-O-Matic'}
  - {id: 1452453066, name: 'Hidden Bar'}
  - {id: 403504866, name: 'PCalc'}
  - {id: 568494494, name: 'Pocket'}
  - {id: 1498497896, name: 'Raivo OTP'}
  - {id: 1477385213, name: 'Save to Pocket'}
  - {id: 585829637, name: 'Todoist: To-do list & Planner'}
  - {id: 1463298887, name: 'Userscripts'}
  - {id: 497799835, name: 'Xcode'}

mas_uninstalled_apps:
  - {id: 682658836, name: 'GarageBand'}
  - {id: 408981434, name: "iMovie"}
  - {id: 409203825, name: "Numbers"}
  - {id: 409201541, name: "Pages"}
  - {id: 1482490089, name: 'Tampermonkey'}

# Mac Defaults
# ------------
# TODO: Move some of these into defaults of role
mac_defaults_caps_lock_esc: true
mac_defaults_key_repeat_time: 2
mac_defaults_init_key_repeat_time: 8
mac_defaults_keyboard_vscode_key_hold_enabled: false
mac_defaults_key_hold_enabled: true
mac_defaults_keyboard_automatic_spelling_correct: false
mac_defaults_keyboard_auto_quote_subst: false
mac_defaults_keyboard_auto_dash_subst: false
mac_defaults_spotlight_shown: 0  # 0 = hidden, 1 = visible
