---
# pip - no longer works in python 3.11
# pip_installed_packages:
#   - docker


# Networking
svartalv_main_domain: "{{ vault_svartalv_main_domain }}"

# pip
pip_install_docker: true

# Monitoring
## Fail2ban
fail2ban_destemail: "{{ admin_email }}"  # Email to send notifications to
fail2ban_sendername: fail2ban  # Name of sender
fail2ban_sender: "{{ fail2ban_sendername }}@{{ svartalv_main_domain }}"
fail2ban_services:
  - name: sshd
    enabled: true
    port: "{{ ssh_target_port }}"  # Secret hidden in out of tree inventory
    logpath: /var/log/auth.log
    maxretry: 3
    bantime: 600
    findtime: 600

## MariaDB/MySQL
mysql_user_home: /root
mysql_user_name: root
mysql_user_password: "{{ vault_postgres_root_password }}"
mysql_enabled_on_startup: true
mysql_users:
  - name: "{{ admin_user }}"
    password: "{{ ansible_become_password }}"
    state: present

# Dotfiles
## Bash
bash_set_default_shell: true
dotfiles_bash_git_force: true

## Vim
vim_git_force: true
vim_git_backup: false

## TMux
tmux_git_force: true
tmux_git_backup: false

# Packages
base_packages:
  - fail2ban
  - git
  - ncdu
  - ranger
  - tree
  - tmux
  - vim
