---
# Cloudflare
cloudflare_valhalla_zoneid: "{{ vault_cloudflare_valhalla_zoneid }}"
cloudflare_dns_token: "{{ vault_cloudflare_dns_token }}"

# Git
git_default_branch: main  # [main]
git_user_name: Marcus Grant
git_user_email: "{{ admin_email }}"
git_pull_rebase: false  # [false]

### Dotfiles ###
# Profile
# profile_paths, earlier items override later ones
profile_paths: [$HOME/.local/bin]

profile_group: "{{ admin_user }}"
profile_xdg_include: true
profile_ls_colors: cxexfxdxBxEhebAbAgAcAd
profile_d_path: ~/.config/profile.d
profile_editor: nvim
profile_envs:
  - {name: CARGO_HOME, value: $XDG_DATA_HOME/cargo}
  - {name: PNPM_HOME, value: $XDG_DATA_HOME/pnpm}
  # - {name: PYENV_ROOT, value: $XDG_DATA_HOME/pyenv}  # DELETEME: Moved to pyenv role
profile_custom_entries:
  - "{{ '#' }} Secrets"
  - "export EMAIL='{{ admin_email }}'"
  # - 'eval "$(pyenv init -)"'  # DELETEME: if this works with pyenv role, remove

base_packages:
  - fail2ban
  - git
  - jq
  - ncdu
  - ranger
  - tree
  - tmux
  - vim
  - zsh

