---
# tasks file for collections/dotfiles/roles/profile
- name: Ensure profile.d directory exists
  ansible.builtin.file:
    path: "{{ profile_d_path }}"
    state: directory
    owner: "{{ profile_user }}"
    group: "{{ profile_group }}"
    mode: 0750

- name: Template profile file
  ansible.builtin.template:
    src: profile.j2
    dest: "~/.profile"
    owner: "{{ profile_user }}"
    group: "{{ profile_group }}"
    mode: 0640
  notify: Reload Shell

