---
# tasks file for marcus_grant.ops.restic
- name: Install restic
  ansible.builtin.package:
    name: "{{ restic_package }}"
    state: present
  loop_control: {loop_var: restic_package}
  loop: >
    {{ restic_pkgs[ansible_os_family] |
      default(restic_pkgs_d) +
      restic_extra_pkgs }}

# - name: Template env files for each repository
#   ansible.builtin.template:
#     src: env.j2
#     dest: "{{ restic_env_dir }}/{{ restic_env_file.name }}"
#     owner: "{{ ansible_user }}"
#     mode: '0600'
#   loop: "{{ restic_repos }}"

