---
# tasks file for roles/nginx
- name: Install nginx
  become: true
  ansible.builtin.package:
    name: "{{ nginx_os_package_current }}"
    state: present
  loop_control: {loop_var: nginx_os_package_current}
  loop: "{{ nginx_os_packages[ansible_os_family] | default(['nginx']) }}"
  notify: Reload nginx

- name: Copy nginx config
  become: true
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx

# FIXME: What the hell is an end of comment tag in jinja templates?
- name: Template nginx-reload-on-change script
  become: true
  ansible.builtin.template:
    src: nginx-reload-on-change.sh
    dest: /usr/local/bin/nginx-reload-on-change
    owner: root
    group: root
    mode: 0755
  when: nginx_reload_daemon_enabled
