---
# tasks file for marcus_grant.dotfiles.userdirs
- name: Set fact for profile_d path to use by checking two vars & final default
  ansible.builtin.set_fact:
    userdirs_profd: "{{ profile_d_path | default('~/.config/profile.d') }}"

- name: Debug profile_d_path, userdirs_profd & userdirs_profile_d_path
  ansible.builtin.debug:
    msg: >
      profile_d_path: {{ profile_d_path }},
      userdirs_profd: {{ userdirs_profd }},
      userdirs_profile_d_path: {{ userdirs_profile_d_path | default('undef') }}

- name: Template profile.d/10-userdirs.sh partial profile to be sourced
  ansible.builtin.template:
    src: userdirs.sh.j2
    dest: "{{ userdirs_profile_d_path | default(userdirs_profd) }}/10-userdirs.sh"
    owner: "{{ ansible_env.USER }}"
    mode: 0640
  when: userdirs_xdg_profile_d

# TODO: Consider adding logic so each of the XDG vars being empty strings or None,
# forces the task to ignore that entry.
- name: Ensure XDG directories exist
  ansible.builtin.file:
    path: "{{ userdirs_xdg_dir_path }}"
    state: directory
    mode: '0750'
  loop_control: {loop_var: userdirs_xdg_dir_path }
  loop:
    - "{{ userdirs_xdg_bin_home }}"
    - "{{ userdirs_xdg_data_home }}"
    - "{{ userdirs_xdg_config_home }}"
    - "{{ userdirs_xdg_cache_home }}"
    - "{{ userdirs_xdg_runtime_dir }}"
  when:
    - userdirs_xdg_mkdirs
    - userdirs_xdg_dir_path | length > 0

- name: Create custom directories
  ansible.builtin.file:
    path: "{{ userdirs_custom_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: '0750'
  loop_control: {loop_var: userdirs_custom_dir}
  loop: "{{ userdirs_custom_dirs }}"
  when: userdirs_custom_dirs | length > 0

