---
# Main defaults file for nextcloud role
nextcloud_available_externally: "false"

# Directories
nextcloud_data_directory: "{{ docker_home | default('/mnt/docker') }}/nextcloud"

# Network
nextcloud_port: "8080"
nextcloud_hostname: nextcloud

# Docker
nextcloud_docker_image: nextcloud:22
nextcloud_db_docker_image: postgres:14
nextcloud_cache_docker_image: redis

# Specs
nextcloud_memory: 1g
nextcloud_db_memory: 1g
nextcloud_cache_memory: 1g
