---
# Main defaults file for nextcloud role
nextcloud_enabled: false
nextcloud_available_externally: "false"

# Directories
nextcloud_data_directory: "{{ docker_home | default('/mnt/docker') }}/nextcloud"

# Network
nextcloud_port: "8080"
nextcloud_hostname: nextcloud

# Docker
nextcloud_docker_image: nextcloud
nextcloud_db_docker_image: mariadb

# Specs
nextcloud_memory: 1g
nextcloud_mysql_memory: 1g
