---
# defaults file for marcus_grant.dev.python
# installs
pyenv_install_sys_py: false  # Install python using package manager?
pyenv_extra_sys_pkgs: []  # Install extra system packages in this role
pyenv_root: $HOME/.pyenv  # Location of PyEnv root directory
pyenv_priority: 11  # Profile.d lexical prefix to order loading
pyenv_init: true  # Whether to add pyenv init command to shell
pyenv_versions: []  # Versions of python for pyenv to install
pyenv_version_global: system  # Default global version of python to use
# NOTE: In marcus_grant.dotfile.profile profile_d_path is defined, default to that
# Otherwise it will simply be undefined
pyenv_profile_d_path: "{{ profile_d_path if profile_d_path is defined else omit }}"
