---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600

    - name: "Include gpg"
      include_role:
        name: "gpg"
      vars:
        gpg_extra_packages:
          - pinentry-fltk
        gpg_pinentry_enable: true
        gpg_copy_keyring: true
