---
# tasks file for bash
# Consider the ssh_opts & accept_hostkey option from git module docs below:
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/git_module.html
- name: Ensure bash is installed
  package:
    name: bash
    state: present

- name: Set bash to default shell if bash_set_default_shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/bash
  when: bash_set_default_shell | default('false')

- name: Ensure entire path of directories of bash_dotfiles_dir present
  file:
    path: "{{ bash_dotfiles_dir }}"
    state: directory

# - name: Ensure dotfiles repo is cloned locally
#   git:
#     repo: "{{ bash_dotfiles_url }}"
#     dest: "{{ bash_dotfiles_dir }}"
#     version: "{{ bash_dotfile_version | default('HEAD') }}"
#     update: "{{ bash_dotfiles_update and not bash_dotfiles_set_ssh_remote  }}"
#
# - name: Check current remote URL for local bash dotfile repo
#   shell: "cd {{ bash_dotfiles_dir }} && git remote -v"
#   register: bash_dotfile_git_remote_cmd
#   when:

# - name: Check current remote URL for
