---
galaxy_info:
  author: marcus_grant
  description: Install, configure, manage packages of pip and related packages.

  license: GPL-2.0-or-later

  min_ansible_version: '2.1'

  galaxy_tags: [python, pip, pipx, pyenv, poetry]

# TODO: Determine if tags should be applied to pyenv and skipping them is valid
# Otherwise this might not be a good dependency to include when using pip tag.
# dependencies:  # []
#   - role: marcus_grant.dev.pyenv
