version: "3.6"

services:
  reverb:
    image: reverb:latest
    container_name: reverb
    # environment:
    #   REVERB_PORT: {{ reverb_port }}
    ports:
      - "{{ reverb_port }}:33333"
    restart: unless-stopped
    labels:
      - "traefik.enable={{ reverb_enabled }}"
      - "traefik.http.routers.reverb.rule=Host(`{{ reverb_host }}`)"
      - "traefik.http.routers.reverb.entrypoints=websecure"
      - "traefik.http.routers.reverb.tls=true"
      - "traefik.http.routers.reverb.tls.certresolver=letsencrypt"
      - "traefik.http.services.reverb.loadbalancer.server.port={{ reverb_port }}"
    build:
      context: "{{ reverb_dir }}"
      dockerfile: ./Dockerfile
