---
- name: Check brew exists and its version
  ansible.builtin.command:
    cmd: "{{ homebrew_setup_prefix }}/bin/brew --version"
  changed_when: false
  register: cmd_brew_version
  tags: [homebrew-setup]

- name: Run homebrew install script
  become: true
  ansible.builtin.command:
    argv:
      - /bin/bash
      - -c
      - $(curl
      - -fsSL
      - https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)
    creates: "{{ homebrew_prefix }}/bin/brew"
  async: 5400  # Asynchronously perform task, timeout after 90 minutes
  poll: 30  # Check every 30s
  when: cmd_brew_version.rc != 0
  tags: [homebrew-setup]
