---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: For OS family Debian update apt cache
      apt:
        update_cache: true
        cache_valid_time: 1800
      when: ansible_os_family == 'Debian'
    - name: Install git as dependency to perform install
      package:
        name: git
        state: present
    # - name: 'Put testing configs into bashrc'
    #   ansible.builtin.lineinfile:
    #     path: "{{ ansible_env.HOME }}/.bashrc"
    #     regexp: "{{ item.regexp }}"
    #     line: "{{ item.line }}"
    #   loop:
    #     - regexp: 'asdf\/asdf.sh'
    #       line: '. $HOME/.local/asdf/asdf.sh'
    #     - regexp: 'completions\/asdf.bash'
    #       line: '. $HOME/.local/asdf/completions/asdf.bash'
    #     # . $HOME/.local/share/asdf/asdf.sh
    #     # . $HOME/.local/share/asdf/completions/asdf.bash
    - name: "Include asdf"
      include_role:
        name: "asdf"
      vars:
        asdf_data_dir: ~/.local/asdf
        asdf_config_dir: ~/.config/asdf
        asdf_add_profile_source: true
        # asdf_version: v0.8.1
