---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: For OS family Debian update apt cache
      apt:
        update_cache: true
        cache_valid_time: 1800
      when: ansible_os_family == 'Debian'
    - name: Install git as dependency to perform install
      package:
        name: git
        state: present
    - name: Add user test to test out the asdf_user and the profile.d template
      become: true
      user:
        name: test
        shell: /bin/bash
    - name: "Include asdf"
      include_role:
        name: "asdf"
      vars:
        asdf_user: test
        asdf_data_dir: .local/asdf
        asdf_config_dir: .config/asdf
        asdf_add_profile_source: true
        # asdf_version: v0.8.1


