---
- name: 'Provision the Freyja server, (NOTE) Should be done AFTER bootstrapping'
  hosts: freyja
  gather_facts: true
  become: true
  roles:
    - role: roles/luks
      tags: [drive, block, luks, hdd, sdd, mount, mnt, nas]
    - role: roles/reverb-ddns
      tags: [reverb, cron, ddns, ip, url, domain, dns]
