---
- hosts: odin
  connection: local
  gather_facts: true
  become: true
  environment:
    PATH: "$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
  roles:
    - role: elliotweiser.osx-command-line-tools
      tags: [mac, xcode, clitools, pre]
    # - role: geerlingguy.mac.homebrew
    #   tags: [mac, homebrew, brew, packages]
    # - role: marcus-grant.dotfiles.
    - role: roles/mac-config
      tags: [mac, properties, system, keyboard]
    - role: roles/fonts
      tags: [font, fonts, ui]
  # post_tasks:
  #   - 