---
- name: Configurate Baldr macOS workstation
  hosts: baldr
  connection: local
  gather_facts: true
  roles:
    - role: marcus_grant.macos.homebrew_setup
      tags: [homebrew-setup, bootstrap, homebrew, brew, setup]
    - role: marcus_grant.ops.ssh
      tags: [ssh, ops, shell, remote, manage]
    - role: marcus_grant.dev.git
      tags: [git, dotfile, ops, dev]
    - role: marcus_grant.dotfiles.profile
      tags: [profile, dotfile, shell]
    - role: marcus_grant.dotfiles.userdirs
      tags: [userdirs, dotfile, shell, directory]
    - role: marcus_grant.dotfiles.zsh
      tags: [zsh, dotfiles, dots, shell]
    - role: marcus_grant.dev.pyenv
      tags: [pyenv, python, dev, ops]
    - role: marcus_grant.ops.restic
      tags: [restic, backup]
    - role: mac-defaults  # TODO: Move to macos collection
      tags: [properties, config, default, system, keyboard]
    - role: marcus_grant.macos.homebrew
      tags: [homebrew, brew, package, cask, tap, install]
    - role: marcus_grant.macos.mas
      tags: [mas, app, apps, store, install, uninstall]
    - role: fonts
      tags: [font, ui]

# - hosts: odin
#   environment:
#     PATH: "$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
#   roles:
#     # - role: marcus_grant.dotfiles.neovim
#     #   become_user: "{{ admin_user }}"
#     #   tags: [nvim, neovim, dotfiles, dots]
