---
- name: Configurate Baldr macOS workstation
  hosts: baldr
  connection: local
  gather_facts: true
  roles:
    - role: marcus_grant.macos.homebrew_setup
      tags: [homebrew-setup, bootstrap, homebrew, brew, setup]
    - role: marcus_grant.dotfiles.profile
      tags: [profile, dotfile, shell]
    - role: mac-defaults  # TODO: Move to macos collection
      tags: [properties, config, default, system, keyboard]
    - role: marcus_grant.macos.homebrew
      tags: [homebrew, brew, package, cask, tap, install]
    - role: marcus_grant.macos.mas
      tags: [mas, app, apps, store, install, uninstall]
    - role: fonts
      tags: [font, ui]

# - hosts: odin
#   connection: local
#   gather_facts: true
#   become: true
#   environment:
#     PATH: "$HOME/Library/Python/3.8/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"
#   # pre_tasks:
#   roles:
#     - role: collections/marcus_grant/dotfiles/roles/git
#       tags: [dots, dotfiles, git, gh, github, ssh]
#     # TODO: These dotfiles roles fail even when *_git_force is false when git module attempts to clone preexisting repos
#     # - role: marcus_grant.dotfiles.zsh
#     #   become_user: "{{ admin_user }}"
#     #   tags: [zsh, dotfiles, dots]
#     # - role: marcus_grant.dotfiles.neovim
#     #   become_user: "{{ admin_user }}"
#     #   tags: [nvim, neovim, dotfiles, dots]
