---
roles:
  - geerlingguy.docker
  - name: elliotweiser.osx-command-line-tools
    type: git
collections:
  - name: community.general
  - name: https://github.com/marcus-grant/ansible-collection-dotfiles
    type: git
  - name: geerlingguy.mac