---
- hosts: all
  gather_facts: true
  become: true
  roles:
    - role: marcus_grant.dotfiles.bash
      tags: [dots, dotfiles, bash]
    - role: marcus_grant.dotfiles.not_coreutil
      tags: [dots, dotfiles, coreutil, fd, rg, ripgrep, fzf]
    - role: marcus_grant.dotfiles.vim
      tags: [dots, dotfiles, vim]
    - role: geerlingguy.docker
      tags: [docker]

- hosts: all
  gather_facts: true
  roles:
    - role: marcus_grant.dotfiles.bash
      tags: [dots, dotfiles, bash]
    - role: marcus_grant.dotfiles.vim
      tags: [dots, dotfiles, vim]
