---
- name: 'Provision hetzner servers, NOTE: Should be done AFTER bootstrapping'
  hosts: brokkr
  gather_facts: true
  become: true
  vars:
    caddy_github_token: "{{ vault_github_token }}"
  pre_tasks:
    # TODO Turn these into a(n) role(s)
    - name: Change root password
      ansible.builtin.user:
        name: root
        update_password: always
        password: "{{ root_password | password_hash('sha512') }}"
    - name: Remove PasswordAuthentication from sshd_config
      become: true
      ansible.builtin.replace:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication\ yes'
        replace: 'PasswordAuthentication no'
      tags: [init, ssh, security]
      register: sshd_config_result
    # TODO make handler
    - name: Restart sshd 
      ansible.builtin.service:
        name: sshd
        state: restarted
      when: sshd_config_result.changed
      tags: [skip_ansible_lint]
    - name: Install initial packages in packages_installed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        state: present
        name: "{{ item }}"
      loop: "{{ packages_installed }}"
      tags: [init, apt, pkgs, packages]
  roles:
    - role: roles/pip
      tags: [init, python, pip]
    - role: roles/fail2ban
      tags: [init, security, fail2ban]
    - role: geerlingguy.postgresql
      tags: [db, postgres, psql, database, postgresql]
    - role: geerlingguy.mysql
      tags: [db, mysql, mariadb]
    - role: geerlingguy.docker
      tags: [docker, server, service, container]
    - role: roles/caddy
      tags: [caddy,web,server,service,proxy,selfhost]
    - role: roles/podman/podman-init
      tags: [podman,server,service,container,selfhost]
    - role: roles/podman/reverb
      tags: [podman,server,service,container,selfhost,reverb,ip,echo]
