---
# === COMMON SVARTALV ===
- name: '[ALL SVARTALV] Provision hetzner servers, NOTE: Should be done AFTER bootstrapping'
  hosts: brokkr
  gather_facts: true
  become: true
  roles:
    - role: root-password
      tags: [init, security, root, password]
    - role: ssh-server-key-only
      tags: [init, ssh, server, security]
    - role: base-packages
      tags: [init, apt, package]
    - role: pip-install
      tags: [init, python, pip]
    - role: fail2ban
      tags: [init, security, fail2ban]
    - role: podman-init
      tags: [podman, server, service, container]
    - role: geerlingguy.docker
      tags: [docker, server, service, container]

# === BROKKR ONLY ===
- name: '[BROKKR ONLY] Provision hetzner servers, NOTE: Should be done AFTER bootstrapping'
  hosts: brokkr
  become: true
  roles:
    - role: caddy-docker-proxy
      tags: [caddy, server, proxy, tls, cert]
    # - role: traefik
    #   tags: [traefik, server, proxy, selfhost, ssl, cert]
    # - role: whoami
    #   tags: [traefik, server, container, whoami, ip]
#     - role: caddy
#       tags: [caddy, web, server, service, proxy, selfhost]
#     - role: reverb
#       tags: [server, service, container, reverb, ip]
#     - role: geerlingguy.postgresql
#       tags: [database, postgres]
#     - role: geerlingguy.mysql
#       tags: [database, mysql, mariadb]

# DEV ONLY
# - name: '[DEV ONLY] Provision hetzner servers, NOTE: Should be done AFTER bootstrapping'
#   hosts: brokkr
#   gather_facts: true
#   become: true
#   vars:
#     caddy_github_token: "{{ vault_github_token }}"
