---
# Valhalla group playbook
# === COMMON Valhalla ===
- name: '[ALL VALHALLA ROOT] Provision valhalla servers, NOTE: Assumed bootstrapped'
  hosts: [frigg] # TODO: Make this work with jord
  gather_facts: true
  become: true
  roles:
    - {role: base-packages, tags: [apt, package]}
    - {role: marcus_grant.dev.git, tags: [git, dotfile, ops, dev, deploy]}
    - {role: geerlingguy.docker, tags: [docker, server, service, container]}
    - {role: docker_config, tags: [docker-config, docker, config]}

    # - {role: pip-install, tags: [python, pip]}
    # - {role: fail2ban, tags: [security, fail2ban]}
    # - {role: podman-init, tags: [podman, server, service, container]}
    # tags: [svartalv-common, base-config, server, container, init]

- name: '[ALL VALHALLA ADMIN] Provision valhalla servers, NOTE: SSH User'
  hosts: [frigg] # TODO: Make this work with jord
  gather_facts: true
  become_user: "{{ admin_user }}"
  pre_tasks:
    - name: Gather facts, to override root ones, incase fact caching enabled
      ansible.builtin.setup: { gather_timeout: 10 }
      tags: [always]
  roles:
    - {role: marcus_grant.dev.git, tags: [git, dotfile, ops, dev, deploy]}
    - {role: marcus_grant.dotfiles.profile, tags: [profile, dotfile, shell]}
    - {role: marcus_grant.dotfiles.userdirs, tags: [userdir, dir, profile, dotfile, xdg]}
    - {role: marcus_grant.dotfiles.zsh, tags: [zsh, dotfile, shell]}
    - {role: marcus_grant.dotfiles.neovim, tags: [neovim, nvim, dotfiles, dev]}

# === FRIGG ONLY ===
# - name: '[FRIGG ONLY] Provision frigg server'
#   hosts: brokkr
#   become: true
#   roles:
    # - {role: restic_docker, tags: [restic_docker, backup, restic]}
    # - {role: docker_postgres, tags: [docker_postgres, postgres, db, data, net]}
    # - {role: restic_postgres, tags: [restic_postgres, postgres, db, data, restic, backup]}
    # - {role: pgadmin, tags: [pgadmin, postgres, db, data, ui]}
    # - {role: nginx-certbot, tags: [nginx, certbot, letsencrypt, tls, proxy, net]}
    # - role: whoami
    #   tags: [whoami, net]
    # tags: [brokkr-only, server, services, container, web, docker, admin]
