---
- hosts: loki
  gather_facts: true
  become: true
  roles:
    - role: marcus_grant.dotfiles.not_coreutil
      tags: [dotfiles,not_coreutil,coreutil]

    - role: marcus_grant.dotfiles.git
      tags: [dotfiles,git,gitea]
