---
- hosts: loki
  gather_facts: true
  become: true
  roles:
    - role: marcus_grant.dotfiles.not_coreutil
      tags: [dotfiles,not_coreutil,coreutil]

    - role: marcus_grant.dotfiles.git
      tags: [dotfiles,git,gitea]

    - role: marcus_grant.dotfiles.bash
      tags: [dotfiles,bash]
      vars:
        dotfiles_bash_default_shell: true

    - role: marcus_grant.dotfiles.vim
      tags: [dotfiles,vim]


- hosts: loki
  gather_facts: true
  become_user: "{{ admin_user }}"
  roles:
    - role: marcus_grant.dotfiles.git
      tags: [dotfiles,git,gitea]

    - role: marcus_grant.dotfiles.bash
      tags: [dotfiles,bash]

    - role: marcus_grant.dotfiles.vim
      tags: [dotfiles,vim]

