---
- hosts: workstation
  gather_facts: true
  become: true
  pre_tasks:
    - name: Full system sync and upgrade (Arch)
      community.general.pacman:
        update_cache: true
        upgrade: true
      become: true
      when: ansible_os_family == 'Archlinux'
      tags: always
  roles:
    - role: marcus_grant.dev.git
      tags: [git, dev, deploy, install]

- hosts: workstation
  gather_facts: true
  roles:
    - role: marcus_grant.dotfiles.profile
      tags: [profile, dotfile, shell, user, env]
    - role: marcus_grant.dotfiles.userdirs
      tags: [profile, dotfile, shell, user, env, xdg]
    - role: marcus_grant.dotfiles.zsh
      tags: [zsh, shell, dotfile, env]
    - role: marcus_grant.dotfiles.neovim
      tags: [neovim, dotfile, shell, dev, editor]
    - role: marcus_grant.dev.pyenv
      tags: [pyenv, python, dotfile, dev, env]
    - role: marcus_grant.dev.pip
      tags: [pip, python, pipx, poetry, dev, dotfile, env]
    - role: marcus_grant.gui.nerd_fonts
      tags: [nerd_fonts, font, gui]
