---
# Podman install/config role roles/podman/tasks/main.yml
- name: Ensure podman installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure podman dependencies are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - uidmap
  when: ansible_os_family == 'Debian'

- name: Ensure podman-compose installed
  ansible.builtin.pip:
    name: podman-compose
    state: present
  when: podman_install_compose

# TODO: This can cause problems when registries changes
# It will recreate the line as if the regexp isn't picking up the key
- name: Cofigure podman registries to search in podman_registries list
  ansible.builtin.lineinfile:
    path: /etc/containers/registries.conf
    regexp: '^unqualified-search-registries'
    line: "unqualified-search-registries = [{{ podman_registries | join(', ') }}]"
    owner: root
    group: containers
    mode: 0774
  when:
    - podman_registries is defined
    - podman_registries | length > 0

- name: Ensure group named group for pods or containers exists
  ansible.builtin.group:
    name: "{{ podman_group }}"
    gid: "{{ podman_gid }}"
    state: present

- name: Add any additional groups for podman
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ podman_extra_groups }}"
  when:
    - podman_extra_groups is defined
    - podman_extra_groups | length > 0

- name: Add extra users to default general group for all containers
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ podman_group }}"
    append: true
  loop: "{{ podman_group_users }}"
  when:
    - podman_group_users is defined
    - podman_group_users | length > 0
