---
# Podman install/config role roles/podman/tasks/main.yml
- name: Ensure podman installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure group named group for pods or containers exists
  ansible.builtin.group:
    name: "{{ podman_group }}"
    gid: "{{ podman_gid }}"
    state: present

- name: Add any additional groups for podman
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ podman_extra_groups }}"
  when:
    - podman_extra_groups is defined
    - podman_extra_groups | length > 0

- name: Add extra users to default general group for all containers
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ podman_group }}"
    append: true
  loop: "{{ podman_group_users }}"
  when:
    - podman_group_users is defined
    - podman_group_users | length > 0
