---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ~/.config/nycklar/a
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
