---
# Main tasks file for role/podman/reverb
- name: Ensure reverb user exists with home and group
  ansible.builtin.user:
    name: reverb
    uid: "{{ reverb_uid | default(omit) }}"

- name: Ensure the podman general group (default containers) has ownership of home
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "/home/reverb"
    group: "{{ podman_group }}"

- name: Git checkout reverb (main) to reverb home
  ansible.builtin.git:
    repo: https://github.com/marcus-grant/reverb
    dest: /home/reverb/repo
    force: "{{ reverb_git_force }}"
    update: "{{ reverb_git_update }}"
    version: main

- name: Chown and ghgrp the reverb repo for reverb user & containers group
  ansible.builtin.file:
    state: directory
    path: /home/reverb/repo
    recurse: true
    owner: reverb
    group: "{{ podman_group }}"
    mode: 0770
