---
# defaults file for roles/restic-docker-postgres-backup
restic_postgres_dir: /opt/restic-postgres  # Workind dir for restic-postgres
restic_postgres_pguser: postgres  # super user name for postgres
restic_postgres_pgpassword: postgres  # super user password for postgres
restic_postgres_pghost: postgres  # docker network hostname for postgres
restic_postgres_docker_net: postgres  # docker network name for postgres
restic_postgres_machine_hostname: postgres  # hostname of machine (for restic names)
restic_postgres_b2_app_key_id: ""  # Required, B2 key ID that can reach bucket
restic_postgres_b2_app_key: ""  # Required, B2 key that can reach bucket
restic_postgres_repo: ""  # Required, B2 URL to bucket
restic_postgres_repo_password: ""  # Required, Password for restic repo
restic_postgres_repo_compression: auto
restic_postgres_dump_filename: postgres-dumpall.sql  # Filename for dumpall
restic_postgres_keep_last: 10  # Number of last backups (any kind) to keep
restic_postgres_keep_daily: 7  # Number of last daily backups to keep
restic_postgres_keep_weekly: 3  # Number of last weekly backups to keep
restic_postgres_keep_monthly: 10  # Number of last monthly backups to keep
restic_postgres_keep_yearly: 5  # Number of last yearly backups to keep
restic_postgres_schedule: "*-*-* 03:00:00 UTC"  # Cron string for backup schedule
restic_postgres_restore_table: restic_restore  # Name of table that tracks restores
