#SPDX-License-Identifier: MIT-0
---
- name: Install Nerd Fonts on Linux
  ansible.builtin.include_tasks: install_linux.yml
  when: ansible_facts['os_family'] != 'Darwin' 

- name: Install Nerd Fonts on macOS
  ansible.builtin.include_tasks: install_macos.yml
  when: ansible_facts['os_family'] == 'Darwin'

