---
# Main tasks file of WordPress role
- name: Create user for WordPress files and capibilities assignments
  user:
    name: wordpress
    comment: For use with wordpress services only
    uid: "{{ wordpress_uid | int }}"
  when: wordpress_uid is defined

- name: Create WordPress directories
  file:
    path: "{{ item }}"
    state: directory
    # TODO find a better default behavior
    owner: "{{ wordpress_uid | default('999') }}"
    group: docker
    mode: 0755
  loop:
    - "{{ wordpress_data_directory }}"
    - "{{ wordpress_data_directory }}/db"
    - "{{ wordpress_data_directory }}/wp"
    # - "{{ wordpress_data_directory }}/wp/wp-content"
    # - "{{ wordpress_data_directory }}/wp/wp-content/themes"
    # - "{{ wordpress_data_directory }}/wp/wp-content/plugins"

- name: Create the Docker network wp-net for Wordpress related containers
  docker_network:
    name: wp-net

- name: Start the MariaDB database container before Wordpress container
  docker_container:
    name: wp-db
    image: "{{ wordpress_db_docker_image }}"
    pull: true
    restart_policy: unless-stopped
    user: "{{ wordpress_uid | default(omit) }}"
    volumes:
      - "{{ wordpress_data_directory }}/db:/var/lib/mysql:rw"
    networks:
      - name: wp-net
    env:
      MYSQL_ROOT_PASSWORD: "{{ wordpress_db_password }}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "{{ wordpress_db_password }}"
    # TODO: Setup management for container memory use
    # memory: "{{ wordpress_db_memory }}"

- name: Run the WordPress container
  docker_container:
    name: wp-app
    image: "{{ wordpress_docker_image }}"
    pull: true
    restart_policy: unless-stopped
    user: "{{ wordpress_uid | default(omit) }}"
    volumes:
      - "{{ wordpress_data_directory }}/wp:/var/www/html"
    networks:
      - name: wp-net
    ports: "{{ wordpress_port }}:80"
    env:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "{{ wordpress_db_password }}"
      WORDPRESS_DB_NAME: wordpress
    labels:
      traefik.enable: "{{ wordpress_available_externally }}"
      traefik.http.routers.wordpress.rule: "Host(`{{ wordpress_subdomain }}.{{ server_base_domain }}`)"
      traefik.http.routers.wordpress.tls.certresolver: "letsencrypt"
      traefik.http.routers.wordpress.tls.domains[0].main: "{{ server_base_domain }}"
      traefik.http.routers.wordpress.tls.domains[0].sans: "*.{{ server_base_domain }}"
      traefik.http.services.wordpress.loadbalancer.server.port: "80"
    # TODO: Setup management for container memory use
    # memory: "{{ wordpress_db_memory }}"