---
# TODO: Make this role capable of adding pgadmin user on hba & pg users
# tasks file for roles/postgresql-pgadmin
- name: Ensure docker volume pgadmin exists
  community.docker.docker_volume:
    name: pgadmin
    state: present

- name: Template pgadmin docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /etc/docker/compose/pgadmin.yml
    owner: "{{ pgadmin_uid }}"
    group: "{{ pgadmin_gid }}"
    mode: 0640
  notify: Apply pgadmin service

- name: Template pgadmin service file
  become: true
  ansible.builtin.template:
    src: pgadmin.service
    dest: /etc/systemd/system/pgadmin.service
    owner: root
    group: root
    mode: 0644
  notify: Apply pgadmin service
