---
# TODO: Make this role capable of adding pgadmin user on hba & pg users
# tasks file for roles/postgresql-pgadmin
- name: Ensure pgadmin directories exist
  ansible.builtin.file:
    path: "{{ pgadmin_dir }}"
    state: directory
    owner: "{{ pgadmin_uid }}"
    group: "{{ pgadmin_gid }}"
    mode: 0755
  loop_control: {loop_var: pgadmin_dir}
  loop: [/opt/pgadmin, /opt/pgadmin/data]

- name: Template pgadmin docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /opt/pgadmin/docker-compose.yml
    owner: "{{ pgadmin_uid }}"
    group: "{{ pgadmin_gid }}"
    mode: 0644
  notify: Apply pgadmin service

- name: Template pgadmin service file
  become: true
  ansible.builtin.template:
    src: pgadmin.service
    dest: /etc/systemd/system/pgadmin.service
    owner: root
    group: root
    mode: 0644
  notify: Apply pgadmin service
