---
# Main tasks file for role/podman/reverb
- name: Ensure reverb user exists with home and group
  ansible.builtin.user:
    name: reverb
    uid: "{{ reverb_uid | default(omit) }}"

- name: Ensure the podman general group (default containers) has ownership of home
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "/home/reverb"
    group: "{{ podman_group }}"

- name: Git checkout reverb (main) to reverb home
  ansible.builtin.git:
    repo: https://github.com/marcus-grant/reverb
    dest: /home/reverb/repo
    force: "{{ reverb_git_force }}"
    update: "{{ reverb_git_update }}"
    version: main

- name: Chown and ghgrp the reverb repo for reverb user & containers group
  ansible.builtin.file:
    state: directory
    path: /home/reverb/repo
    recurse: true
    owner: reverb
    group: "{{ podman_group }}"
    mode: 0770

# TODO: When debian has newer better supported podman tooling might come back here
# - name: Template a container-compose file
#   ansible.builtin.template:
#     src: podman-compose.yml.j2
#     dest: /home/reverb/container-compose.yml
#     owner: reverb
#     group: containers
#     mode: 0770

- name: Build the docker container version of the server
  community.docker.docker_image:
    name: localhost/reverb
    build:
      path: /home/reverb/repo
    source: build

- name: Run the server in docker
  community.docker.docker_container:
    name: reverb
    image: localhost/reverb
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ reverb_port }}:33333"

- name: Template caddy route file in sites-available
  ansible.builtin.template:
    src: reverb.Caddyfile.j2
    dest: /etc/caddy/sites-available/reverb.Caddyfile
    owner: reverb
    group: caddy
    mode: 0774
  notify: Restart caddy

- name: Link caddy route to sites-enabled
  ansible.builtin.file:
    src: /etc/caddy/sites-available/reverb.Caddyfile
    dest: /etc/caddy/sites-enabled/reverb.Caddyfile
    owner: reverb
    group: caddy
    mode: 0774
    state: link
