---
# Role traefik defaults
# Whether to turn on or off traefik idempotently.
# Not some kind of certification resolution will be necessary
# Main
traefik_enable: true  # Enable systemd service, and container restart policy
traefik_debug: false  # Sets debug api, debug lvl logs & staging acme server

# Docker
traefik_docker_image: traefik:v2.10  # Docker image to use with tag
traefik_docker_network: traefik  # Docker network to attach to

# Logs
traefik_log_level: INFO  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC

# Certificate Resolver
traefik_cert_resolver_name: 'letsencrypt'  # Reference to configured resolver
traefik_cert_email: ''  # The email address associated to the certificate

# Environment variables (also used to specify DNS ACME provider)
traefik_environment: {}
#  CF_DNS_API_TOKEN: 'deadbeef1234567890'  # Example entry
