---
# Main tasks file of nextcloud role
- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: docker
  loop:
    - "{{ nextcloud_data_directory }}/nextcloud"
    - "{{ nextcloud_data_directory }}/mysql"

- name: Nextcloud MariaDB Docker container
  docker_container:
    name: nextcloud-mysql
    image: "{{ nextcloud_db_docker_image }}"
    pull: true
    volumes:
      - "{{ nextcloud_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_sql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_sql_password }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_sql_root_password }}"
    restart_policy: unless-stopped
    # TODO: Setup management for container memory use
    # memory: "{{ nextcloud_mysql_memory }}"
