---
- name: Create postgres data volume for /var/lib/postgresql/data
  become: true
  community.docker.docker_volume:
    name: "{{ docker_postgres_volume_name }}"
    state: present

- name: Create docker network
  become: true
  community.docker.docker_network:
    name: "{{ docker_postgres_net }}"
    state: present

- name: Template docker-compose file for PostgreSQL container
  become: true
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ docker_postgres_compose_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Apply postgres container docker-compose service

- name: Template systemd service file to docker-compose PostgreSQL container
  ansible.builtin.template:
    src: docker-postgres.service
    dest: /etc/systemd/system/docker-postgres.service
    owner: root
    group: root
    mode: 0644
  notify: Apply postgres container docker-compose service
