---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # TODO: Find way to make this work on macOS
  # - name: arch
  #   image: archlinux
  #   pre_build_image: true
  # - name: debian
  #   image: debian:11
  #   pre_build_image: true
  - name: debian
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  echo YAML lint successful
  ansible-lint
  echo Ansible lint successful

#   ansible-test sanity
#   echo Ansible test sanity successful