version: '3.7'
services:
  pgadmin:
    container_name: pgadmin
    image: "{{ pgadmin_image }}"
    volumes:
      - /opt/pgadmin/data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_default_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_default_password }}"
    ports:
      - "{{ pgadmin_port }}:80"
    networks:
      - "{{ pgadmin_postgres_docker_network }}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  {{ pgadmin_postgres_docker_network }}:
    name: {{ pgadmin_postgres_docker_network }}
    external: true
