#SPDX-License-Identifier: MIT-0
---
# defaults file for nerd_fonts
nerd_fonts_dir: ~/.local/share/fonts
nerd_fonts_dicts:
  - name: FiraCode
    file: FiraCode.zip
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip"
  - name: SourceCodePro
    file: SourceCodePro.zip
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/SourceCodePro.zip"

# Only for macos which uses homebrew package names
nerd_fonts_list:
  - font-fira-code-nerd-font
  - font-hack-nerd-font
