---
- name: Converge
  hosts: all
  tasks:
    - name: "Include neovim"
      vars:
        nvim_git_repo: https://github.com/marcus-grant/dots-neovim4
        # zsh_rc_file: rc.zsh
        # zsh_profile_file: profile.zsh
        # zsh_env_file: env.zsh
        zsh_default_shell: true
        zsh_git_force: true
        # zsh_git_backup: true
      ansible.builtin.include_role:
        name: "neovim"
