---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Check installed packages ansible fact
    ansible.builtin.package_facts: manager=auto

  # - name: Assert neovim is installed
  #   ansible.builtin.assert:
  #     that: ansible_facts.packages['neovim']

  - name: Check 

  - name: Register stat module for default nvim_config_dir at /root/.config/nvim
    ansible.builtin.stat:
      path: /root/.config/nvim
    register: nvim_path

  - name: Assert that nvim_path exists as directory
    ansible.builtin.assert:
      that: nvim_path.stat.isdir

  - name: Register current git remote of /root/.config/nvim
    ansible.builtin.shell: 'cd /root/.config/nvim; git remote -v'
    changed_when: false
    register: shell_git_remote

  - name: Assert that either a SSH or HTTPS git remote exists on repo
    ansible.builtin.assert:
      that: >
        'git@github.com:marcus-grant/dots-neovim4' in shell_git_remote.stdout or
        'https://github.com/marcus-grant/dots-neovim4' in shell_git_remote.stdout
  #
  # # - name: Register parent directory of zsh git repo for its contents 
  # #   ansible.builtin.command:
  # #     cmd: "ls -a"
  # #     chdir: /root/.config
  # #   register: zsh_config_parent_dir
  # #   changed_when: false
  # #
  # # - name: Assert the backed up zsh dotfile repo exists
  # #   # ansible.builtin.debug: var=zsh_config_parent_dir
  # #   ansible.builtin.assert:
  # #     that: zsh_config_parent_dir.stdout_lines | length > 3
  #
  # - name: Register stat for zshrc
  #   ansible.builtin.stat: path=/root/.zshrc
  #   register: zsh_rc
  #
  # - name: Register stat for zprofile
  #   ansible.builtin.stat: path=/root/.zprofile
  #   register: zsh_profile
  #
  # - name: Register stat for zshenv
  #   ansible.builtin.stat: path=/root/.zshenv
  #   register: zsh_env
  #
  # - name: Assert that all the expected zsh files are linked to the dotfiles
  #   ansible.builtin.assert:
  #     that:
  #       - item.stat.islnk is defined 
  #       - item.stat.lnk_target is defined
  #       - item.stat.lnk_target == item.dest
  #   loop:
  #     - { stat: "{{ zsh_rc.stat }}", dest: /root/.config/zsh/rc.zsh }
  #     - { stat: "{{ zsh_profile.stat }}", dest: /root/.config/zsh/profile.zsh }
  #     - { stat: "{{ zsh_env.stat }}", dest: /root/.config/zsh/env.zsh }
