---
# Gitea role tasks main

- name: Create Gitea group account
  group:
    name: git
    gid: 1309
    state: present

- name: Create Gitea user account
  user:
    name: git
    uid: 1309
    state: present
    system: true
    update_password: on_create
    create_home: false
    group: git

- name: Create Gitea Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: git
    group: git
    recurse: true
  with_items:
    - "{{ gitea_data_directory }}/gitea"
    - "{{ gitea_data_directory }}/mysql"

- name: Create MySQL container for Gitea
  docker_container:
    name: gitea-mysql
    image: "{{ gitea_db_docker_image }}"
    pull: true
    volumes:
      - "{{ gitea_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "gitea"
      MYSQL_USER: "gitea"
      MYSQL_PASSWORD: "{{ gitea_db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ gitea_db_password }}"
    restart_policy: unless-stopped
    # memory: "{{ gitea_mysql_memory }}"

- name: Create Gitea container
  docker_container:
    name: gitea
    image: "{{ gitea_docker_image }}"
    pull: true
    links:
      - gitea-mysql:db
    volumes:
      - "{{ gitea_data_directory }}/gitea:/data:rw"
    ports:
      - "{{ gitea_port_http }}:3000"
      - "{{ gitea_ssh_port }}:{{ gitea_ssh_port }}"
    env:
      DB_TYPE: "mysql"
      DB_HOST: "db:3306"
      DB_NAME: "gitea"
      DB_USER: "gitea"
      DB_PASSWD: "{{ gitea_db_password }}"
      RUN_MODE: "prod"
      SSH_DOMAIN: "{{ server_base_domain }}"
      SSH_PORT: "{{ gitea_ssh_port }}"
      ROOT_URL: "http://{{ gitea_hostname }}:{{ gitea_port_http }}/"
      USER_UID: "1309"
      USER_GID: "1309"
    restart_policy: unless-stopped
    # memory: "{{ gitea_memory }}"
    labels:
      traefik.enable: "{{ gitea_available_externally }}"
      traefik.http.routers.gitea.rule: >
        Host(`{{ gitea_hostname }}.{{ dev_base_domain }}`)
      traefik.http.routers.gitea.tls.certresolver: "letsencrypt"
      traefik.http.routers.gitea.tls.domains[0].main: >
        {{ dev_base_domain }}
      traefik.http.routers.gitea.tls.domains[0].sans: >
        *.{{ dev_base_domain }}
      traefik.http.services.gitea.loadbalancer.server.port: "3000"
