---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Check installed packages facts
    package_facts: manager=auto

  - name: Assert vim is installed
    assert:
      that: ansible_facts.packages['vim'] is defined

  - name: Register stat of vim git clone destination
    stat:
      path: ~/.config/vim
    register: vimconfigdir
    changed_when: false

  - name: Assert that vim config directory exists
    assert:
      that: vimconfigdir.stat.exists

  - name: Register git remote output for vim dotfiles repo
    command:
      cmd: git remote -v
      chdir: ~/.config/vim
    register: vimgitremote
    changed_when: false
    tags: [skip_ansible_lint]

  - name: Assert that given remote URL for vim dotfiles present
    assert:
      that: "'https://github.com/marcus-grant' in vimgitremote.stdout"


  # - name: Register all current gitconfig values
  #   community.general.git_config:
  #     list_all: true
  #     scope: global
  #   register: gitconfig
  #
  # - name: Assert several config key-value pairs in gitconfig
  #   assert:
  #     that: item.real == item.expected
  #   loop:
  #     - real: "{{ gitconfig.config_values['init.defaultbranch'] }}"
  #       expected: main
  #     - real: "{{ gitconfig.config_values['user.name'] }}"
  #       expected: Ivana Tinkle
  #     - real: "{{ gitconfig.config_values['user.email'] }}"
  #       expected: ivanatinkle@microsoft.com
  #     - real: "{{ gitconfig.config_values['pull.rebase'] }}"
  #       expected: 'false'
