---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update apt_cache
      apt: update_cache=true cache_valid_time=300
      when: ansible_os_family == 'Debian'

    - name: "Include ansible"
      include_role:
        name: "ansible"
