---
# tasks file for marcus_grant.dev.python
- name: Install python
  ansible.builtin.package:
    name: "{{ python_package }}"
    state: present
  loop_control: {loop_var: python_package}
  loop: >
    {{ (python_pkgs[ansible_os_family] |
      default(python_pkgs_d)) +
      python_extra_pkgs }}
  when: python_install_package

# DELETEME?
# - name: Determine if ansible_os_family in python_pyenv_pkgs
#   ansible.builtin.set_fact:
#     python_pyenv_install_with_curl: true
#   when:
#     - python_pyenv_install
#     - ansible_os_family in python_pyenv_pkgs

- name: Install PyEnv via package manager
  ansible.builtin.package:
    name: "{{ python_pyenv_package }}"
    state: present
  loop_control: {loop_var: python_pyenv_package}
  loop: "{{ python_pyenv_pkgs[ansible_os_family] | default([]) }}"
  when:
    - python_pyenv_install
    - not pythone_pyenv_install_curl
    - not (ansible_os_family in python_pyenv_pkgs | default(false))

- name: Install PyEnv via curl & bash
  ansible.builtin.shell:
    cmd: 'set -o pipefail;PYENV_ROOT="{{ python_pyenv_root }}";curl https://pyenv.run|bash'
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
  when:
    - python_pyenv_install
    - python_pyenv_install_curl
    - not (ansible_os_family in python_pyenv_pkgs | default(false))
