# collections/gui/roles/nerd_fonts/meta/main.yml
---
# Author: Marcus Grant
# Description: Galaxy metadata for the nerd_fonts role
#SPDX-License-Identifier: MIT-0

galaxy_info:
  author: Marcus Grant
  description: Installs Nerd Fonts on Linux or macOS
  license: MIT-0
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions: [all]
    - name: Debian
      versions: [all]
    - name: MacOSX
      versions: [all]
  galaxy_tags: [font, nerd-fonts, fonts, terminal, dotfiles]

dependencies: []
