---
# Import and only use old tasks file
# - name: Import old tasks file
#   ansible.builtin.import_tasks: main_old.yml
#   tags: [configuration, fail2ban, fail2ban-import-old-tasks, legacy]
#   when: fail2ban_old_tasks

- name: Check ansible OS family and set fact for package install (default = debian)
  ansible.builtin.set_fact:
    fail2ban_packages: [fail2ban, python3-systemd]
  when: >
    ansible_os_family == 'Debian' or
    not ansible_os_family is defined

# Debian-family prepare tasksfile for fail2ban role or default
- name: Install fail2ban and dependencies using OS package manager
  ansible.builtin.package:
    name: "{{ fail2ban_package }}"
    state: present
  loop: "{{ fail2ban_packages }}"
  loop_control:
    loop_var: fail2ban_package

- name: Ensure fail2ban_conf_dir directory exists (default /etc/fail2ban)
  ansible.builtin.file:
    path: "{{ fail2ban_conf_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  tags: [fail2ban, fail2ban-configure-global]

- name: Template configuration file - /etc/fail2ban/jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: "{{ fail2ban_global_jail_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-configuration
    - fail2ban-configuration-update
