---
- name: Ensure fail2ban is installed
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Template fail2ban configuration
  ansible.builtin.template:
    src: fail2ban.conf.j2
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Template fail2ban jails
  ansible.builtin.template:
    src: jail.conf.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban
