---
##################
### User / Env ###
##################
admin_user_group: sudo  # Used for group permissions

### Profile
profile_user: "{{ admin_user }}"
profile_group: "{{ admin_user }}"
profile_paths: ["$HOME/.local/bin"]
profile_custom_entries:
  - "export PASSWORD_STORE_DIR={{ secrets_path }}/pass"
  - "{{ '#' }} Secrets"
  - "export EMAIL='{{ admin_email }}'"

### ZSH
zsh_git_repo: git@github.com:marcus-grant/dots-zsh.git
zsh_rc_file: rc.zsh
zsh_profile_file: profile.zsh
zsh_env_file: env.zsh
zsh_shell_as_default: true

### NeoVim
neovim_git_repo: git@github.com:marcus-grant/lazyvim.git
neovim_install_method: package # The default method, here for reminder
# NOTE: For debian neovim_pkgs_extra should include libtree-sitter-dev

### Git 
git_default_branch: main # [main]
git_user_name: Marcus Grant
git_user_email: "{{ admin_email }}"
git_pull_rebase: false # [false]

### Bash
dotfiles_bash_repo: git@github.com:marcus-grant/dots-bash
bash_set_default_shell: false
dotfiles_bash_git_force: false

### Vim
vim_git_repo: git@github.com:marcus-grant/dots-vim

### TMux
tmux_git_repo: git@github.com:marcus-grant/dots-tmux


###########
### Dev ###
###########

# PyEnv
pyenv_root: "$HOME/.local/share/pyenv"
pyenv_versions: ["3.9.21", "3.11.11", "3.12.8"]
pyenv_version_global: "3.12.8" # NOTE: This must match one of the versions
# FIXME: Delete this if new pyenv detection of profile_d_path works
# pyenv_profile_d_path: "{{ profile_d_path }}"

# pip
pip_packages_common: [python-dotenv, numpy, pandas, matplotlib, seaborn]
pip_packages_global: [pipx, poetry, jupyter, numpy, pandas, matplotlib, flask, django]

###########
### GUI ###
###########
### Nerdfonts
nerd_fonts_dicts:
  - { name: "FiraCode", url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/FiraCode.zip" }
  - { name: "Iosevka", url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/IosevkaTerm.zip" }
  - { name: "BigBlue", url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/BigBlueTerminal.zip" }

### Flatpak
flatpak_install_gnome_software: true
flatpak_user_flatpaks:
  - org.freecadweb.FreeCAD
  - org.mozilla.firefox
  - com.discordapp.Discord
  - com.mojang.Minecraft
  - org.libretro.RetroArch
  - com.spotify.Client
  - com.usebottles.bottles
  - org.chromium.Chromium
  - com.github.liferooter.textpieces
# flatpak_system_flatpaks:
#   - com.spotify.Client
#   - com.usebottles.bottles
#   - org.chromium.Chromium
#   - com.github.liferooter.textpieces
  
### SSH - TODO: Needs verification
ssh_exclude_hosts: [loki, jord]
ssh_exclude_groups: [mac, hetzner]
# TODO: Better organize these ssh config items
ssh_custom_keys:
  - {
      name: git.key,
      comment: "git@{{ inventory_hostname }}",
      pass: "{{ admin_main_git_password }}",
    }
ssh_git_key: "{{ ssh_custom_keys[0].name }}"
ssh_config_custom_entries:
  - {
      name: jord,
      url: "{{ valhalla_main_domain }}",
      user: root,
      port: "{{ ssh_main_port }}",
    }
  - {
      name: github.com,
      url: github.com,
      user: git,
      key: "{{ ssh_git_key }}",
      agent: true,
    }
  - { name: codeberg.org, user: git, key: "{{ ssh_git_key }}", agent: true }
  - { name: gitlab.com, user: git, key: "{{ ssh_git_key }}" }
  - {
      name: git.marcusgrant.me,
      port: 48513,
      user: git,
      key: "{{ ssh_git_key }}",
      agent: true,
    }
ssh_manual_transfers:
  - { pub: "{{ ssh_git_key }}", location: https://github.com/settings/keys }
  - {
      pub: "{{ ssh_git_key }}",
      location: https://codeberg.org/user/settings/keys,
    }
  - { pub: id_ed25519, location: "{{ hostvars['brokkr']['ansible_host'] }}" }
  - { pub: id_ed25519, location: "{{ hostvars['freyja']['ansible_host'] }}" }
  - {
      pub: id_ed25519,
      location: https://console.hetzner.cloud/projects/1125228/security/sshkeys,
    }

