---
##################
### User / Env ###
##################
admin_user_group: sudo # Used for group permissions

### SSH
# SSH Transfer Keys - Copies from controller to remote
ssh_transfer_key_owner: marcus
ssh_transfer_key_pairs: [{ src: ~/.ssh/git.key }]
# SSH Generate Keys - Generate a key on the host
ssh_keygen_owner: marcus
# SSH Config - Templates config entries for remote
ssh_config_owner: marcus
ssh_config_common_entries: # Atomic configs appended from all
  - "{{ ssh_config_entry_github }}"
  - "{{ ssh_config_entry_codeberg }}"
  - "{{ ssh_config_entry_gitlab }}"

### Git
git_owner: marcus
git_default_branch: main
git_user_name: Marcus Grant
git_user_email: "{{ admin_email }}"
git_pull_rebase: false

### Profile
profile_user: "{{ admin_user }}"
profile_group: "{{ admin_user }}"
profile_paths: ["$HOME/.local/bin"]
profile_custom_entries:
  - "export PASSWORD_STORE_DIR={{ secrets_path }}/pass"
  - "{{ '#' }} Secrets"
  - "export EMAIL='{{ admin_email }}'"

### Userdirs
userdirs_owner: marcus

### ZSH
zsh_owner: marcus
zsh_config_dest: ~/.config/zsh
zsh_git_repo: git@github.com:marcus-grant/dots-zsh.git
zsh_rc_file: rc.zsh
zsh_profile_file: profile.zsh
zsh_env_file: env.zsh
zsh_env_source_profile: true
zsh_shell_as_default: true

### Neovim
neovim_owner: marcus
neovim_git_repo: git@github.com:marcus-grant/lazyvim.git
neovim_git_version: main
# NOTE: Required by nvim-treesitter main branch for parser compilation
# See: https://github.com/nvim-treesitter/nvim-treesitter/issues/8636
neovim_extra_packages: [tree-sitter-cli]

### Vim
vim_git_repo: git@github.com:marcus-grant/dots-vim

### TMux
tmux_git_repo: git@github.com:marcus-grant/dots-tmux

### Python
# PyEnv
pyenv_owner: marcus
pyenv_versions: ["3.13.13", "3.11.15"]
pyenv_global: "3.13.13"
# Pip & Pipx
pip_owner: marcus
pip_pkgs1: [pytest, polars, pandas, numpy, matplotlib, seaborn]
pip_pkgs2: [rich, textual, django, fastapi, pydantic]
pip_packages: "{{ pip_pkgs1 + pip_pkgs2 }}"
pipx_pkgs1: [httpie, posting, harlequin, visidata, yt-dlp, pelican]
pipx_pkgs2: [poetry, jupyterlab, ipython, pre-commit, pgcli, ranger-fm]
pipx_packages: "{{ pipx_pkgs1 + pipx_pkgs2 }}"
# UV
uv_owner: marcus

### Bash - # TODO: Need to verify this role's dotfiles are minimal and safe in a root env
# dotfiles_bash_repo: git@github.com:marcus-grant/dots-bash
# bash_set_default_shell: false
# dotfiles_bash_git_force: false

###########
### GUI ###
###########
### Nerdfonts
nerd_fonts_dicts:
  - name: FiraCode
    file: FiraCode.zip
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.zip"
  - name: Iosevka
    file: IosevkaTerm.zip
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/IosevkaTerm.zip"
  - name: BigBlue
    file: BigBlueTerminal.zip
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/BigBlueTerminal.zip"
