---
# tasks file for marcus_grant.dotfiles.zsh
- name: Include preflight checks for OS family
  ansible.builtin.include_tasks: "preflight-{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'Darwin'

- name: Set fact for zsh packages to ensure are installed
  ansible.builtin.set_fact:
    zsh_pkgs_all: "{{ zsh_pkgs[ansible_os_family] | default(zsh_pkgs_d) + zsh_extra_packages }}"

- name: Ensure zsh is installed (macOS)
  ansible.builtin.package:
    name: "{{ zsh_pkg }}"
    state: present
  loop_control: {loop_var: zsh_pkg}
  loop: "{{ zsh_pkgs_all }}"
  when: ansible_os_family == 'Darwin'

- name: Ensure zsh is installed (*nixes)
  become: true
  become_user: root
  ansible.builtin.package:
    name: "{{ zsh_pkg }}"
    state: present
  loop_control: {loop_var: zsh_pkg}
  loop: "{{ zsh_pkgs_all }}"
  when: ansible_os_family != 'Darwin'

- name: Ensure ZSH dotfile directory parent exists
  ansible.builtin.file:
    path: "{{ zsh_parent_dir }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0750

- name: Register zsh repo git stat
  ansible.builtin.stat:
    path: "{{ zsh_parent_dir }}/{{ zsh_config_dir_name }}/.git"
  register: zsh_git_dir

- name: Git clone the zsh dotfiles repository
  ansible.builtin.git:
    repo: "{{ zsh_git_repo }}"
    version: "{{ zsh_git_version }}"
    force: "{{ zsh_git_force }}"
    dest: "{{ zsh_parent_dir }}/{{ zsh_config_dir_name }}"
  when: not zsh_git_dir.stat.exists or zsh_git_force

- name: Template bare zsh files in root sourcing asocciated file in dotfile dir
  ansible.builtin.template:
    src: "{{ zsh_template_file.src }}"
    dest: "{{ zsh_template_file.dest }}"
    owner: "{{ ansible_user_id }}"
    mode: 0600
  loop_control: {loop_var: zsh_template_file}
  loop:
    - {src: zshrc.j2, dest: "{{ ansible_env.HOME }}/.zshrc"}
    - {src: zshenv.j2, dest: "{{ ansible_env.HOME }}/.zshenv"}
    - {src: zprofile.j2, dest: "{{ ansible_env.HOME }}/.zprofile"}

- name: Set ZSH to be the default shell of ansible user
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_default_shell_path }}"
  when:
    - zsh_shell_as_default
    - ansible_os_family != 'Darwin'
