---
## Podman
podman_group: containers
podman_gid: 10000
podman_group_users: ["{{ admin_user }}"]
podman_install_compose: true
podman_registries: ["'docker.io'"]  # must have single quote around registry

# Reverb
reverb_uid: 10010
reverb_gid: 10010

## Caddy
caddy_github_token: vault_github_token
caddy_create_site_dirs: true
caddy_users_in_group: ["{{ admin_user }}"]
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_systemd_restart_startlimitinterval: "1800"
caddy_systemd_restart_startlimitburst: "15"
caddy_config: |
  # Templated by ansible
  # Import sites-enabled config files/snippets
  import sites-enabled/*
caddy_create_sites: true
caddy_cloudflare_token: "{{ vault_cloudflare_dns_token }}"
caddy_sites:
  - file: hello
    enabled: false
    config: |
      http://hello.{{ svartalv_main_domain }}.com {
        redir @http https://{host}{uri}
      }
      https://hello.{{ svartalv_main_domain }}.com {
        reverse_proxy localhost:12345
      }
  - file: root
    enabled: true
    config: |
      http://www.{{ svartalv_main_domain }} {
        redir https://{host}{uri}
      }
      https://www.{{ svartalv_main_domain }} {
        root * /var/www
        encode gzip
        file_server
      }
