---
# Main configs
## Hostname
hostname: brokkr

# Fail2Ban
fail2ban_sender: "fail2ban@{{ hostname }}.{{ svartalv_main_domain }}"

# Traefik
traefik_docker_image: traefik:v2.10  # Docker image to use with tag
traefik_docker_network: traefik  # Docker network to attach to
traefik_cert_email: '{{ admin_email }}'  # The email address associated to the certificate
traefik_log_level: INFO  # DEBUG, INFO, WARN, ERROR, FATAL, PANIC
traefik_auth_htpasswds: ["{{ admin_htpasswd }}"]

# Nginx
nginx_reload_daemon_enabled: false  # Whether to enable the reload script
nginx_worker_connections: 1024  # Number of connections per worker
