---
## Podman
podman_group: containers
podman_gid: 10000
podman_group_users: ["{{ admin_user }}"]
podman_install_compose: true
podman_registries: ["'docker.io'"]  # must have single quote around registry

# Reverb
reverb_uid: 10010
reverb_gid: 10010
reverb_port: 10010
reverb_git_force: false
reverb_git_update: false

## Caddy
caddy_github_token: vault_github_token
caddy_create_site_dirs: true
caddy_users_in_group: ["{{ admin_user }}"]
caddy_systemd_capabilities_enabled: true
caddy_systemd_capabilities: "CAP_NET_BIND_SERVICE"
caddy_systemd_restart_startlimitinterval: "600"
caddy_systemd_restart_startlimitburst: "5"
caddy_config: |  # look here, undetermined if this really helps http://bit.ly/3Wlt8Cr
  # Templated by ansible
  # Import sites-enabled config files/snippets
  # Root Caddyfile
  {
      auto_https disable_redirects
  }
  http:// {
      redir https://{hostport}{uri} 301
  }
  :80 {
      redir https://{hostport}{uri} 301
  }
  import sites-enabled/*
caddy_create_sites: true
caddy_cloudflare_token: "{{ vault_cloudflare_dns_token }}"
caddy_sites:
  - file: root
    enabled: true
    config: |
      www.{{ svartalv_main_domain }} {
        root * /var/www
        encode gzip
        file_server
      }
