---
# Main configs
## Hostname
hostname: brokkr

# Fail2Ban
fail2ban_sender: "fail2ban@{{ hostname }}.{{ svartalv_main_domain }}"

# PostgreSQL
# Note: postgresql_{user,group} are defined in defaults/main.yml
postgresql_python_library: python3-psycopg2  # For postgresql on python3 sys
# PosgreSQL HBA Entries:
postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
  # Above are defaults, below are custom
  - {type: host, database: all, user: all, address: host.docker.internal, auth_method: md5}
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - {option: log_directory, value: 'log'}
  - {option: listen_addresses, value: '*'}

# PostgreSQL Users:
postgresql_users:
  - name: "{{ admin_user }}"
    password: "{{ postgresql_root_password }}"
    role_attr_flags: "SUPERUSER"
#   - name: pgadmin
#     password: "{{ vault_postgresql_pgadmin_password }}"
#     priv: "ALL"
#     role_attr_flags: "SUPERUSER"
#   - name: restic
#     password: "{{ vault_postgresql_restic_password }}"
#     priv: "ALL"
#     role_attr_flags: "CREATEDB"

# PostgreSQL - PGAdmin Role
postgresql_pgadmin_email: "{{ admin_email }}"
postgresql_pgadmin_password: "{{ postgresql_root_password }}"
postgresql_pgadmin_port: "{{ internal_ports.pgadmin }}"


# Certbot
# Nginx
nginx_certbot_enabled: true  # Whether to enable certbot
nginx_certbot_email: "{{ admin_email }}"
nginx_reload_daemon_enabled: false  # Whether to enable the reload script
nginx_worker_connections: 1024  # Number of connections per worker
# Nginx - Site configs
nginx_sites:
  - url: "whoami.{{ svartalv_main_domain }}"
    enabled: true
    port: "{{ internal_ports.whoami }}"
    ssl: true
    redirect_http: true
    redirect_www: true
    extra: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      client_max_body_size 100m;
  - url: "pgadmin.{{ svartalv_main_domain }}"
    enabled: true
    port: "{{ internal_ports.pgadmin }}"
    ssl: true
    redirect_http: true


# Docker-Compose Systemd Services
# Whoami
whoami_port: "{{ internal_ports.whoami }}"
