---
# LUKS
# For mount options look at this useful guide for btrfs:
# https://linuxhint.com/btrfs-filesystem-mount-options/
luks_mappings:
  - mount: /mnt/drv/cold
    mount_opts: defaults,noatime,space_cache=v2,compress=zstd
    volume: /dev/coldvg/coldlv
    luks_map: crypt-cold
    block_id: d69ed19e-4c8d-4a2b-821a-4a0411184da9
  - mount: /mnt/drv/cold/vids
    mount_opts: defaults,noatime,space_cache=v2
    volume: /dev/coldvg/vidslv
    luks_map: crypt-vids
    block_id: 9e6fe5c2-d54e-4608-a783-6ccf8770cced
  - mount: /mnt/drv/hot
    mount_opts: >- # space cache v1 for sub 2TB, v2 for more than
      defaults,ssd,noatime,discard,space_cache=v1,compress=zstd
    volume: /dev/hotvg/hotlv
    luks_map: crypt-hot
    block_id: e4b08bac-2e0b-42f3-aea7-d8e351cc5632
  - mount: /mnt/drv/db
    mount_opts: defaults,noatime,discard  # XFS (no btrfs opts)
    volume: /dev/hotvg/dblv
    luks_map: crypt-db
    block_id: 8814ecde-8532-4efe-8c6a-db6fac2f3286
  - mount: /mnt/drv/vm
    mount_opts: defaults,noatime,discard  # XFS (no btrfs opts)
    volume: /dev/hotvg/vmlv
    luks_map: crypt-vm
    block_id: e75bcda6-66bc-4bda-986d-bb243642ea8b