# host_vars/thor.yml
---
# Author: Marcus Grant
# Description: Host variables for Thor workstation (Framework Desktop, Ryzen AI Max+ 395)

# Git
# ---
git_extra_packages: [github-cli, lazygit, git-lfs, git-crypt]

# SSH
# ---
# SSH Config
_ssh_cfgs:
  - "{{ ssh_config_entry_heimdall_opn }}"
  - "{{ ssh_config_entry_heimdall_pve }}"
ssh_config_host_entries: >-
  {{ _ssh_cfgs | map('combine', {'identity_file': '~/.ssh/id_ed25519'}) | list }}
# Add more config dicts here...
# ZSH
# ---
zsh_extra_packages: [starship, bat, curl, fd, fzf, ripgrep, atuin, wl-clipboard]

# XDG / .dist scaffold
# ---
userdirs_xdg_cache_home: .dist/arch/cache
userdirs_xdg_config_home: .dist/arch/config
userdirs_xdg_data_home: .dist/arch/local
userdirs_user_dirs_enabled: true
userdirs_custom_dirs:
  [~/doc, ~/pic, ~/video, ~/audio, ~/game, ~/project, ~/inbox]
userdirs_user_dirs:
  documents: doc
  pictures: pic
  videos: video
  music: audio
  download: inbox
  desktop: Desktop
  templates: Templates
  publicshare: Public

# PyEnv
# -----
pyenv_root: ~/state/pyenv

# uv
# --
uv_link_mode: hardlink
