---
# Docker
# ------

# NOTE fixes a bug in geerlingguy.docker where instead of giving 'ubuntu'
# ... as ansible_distribution which docker expects in its url it gives pop!_os
# yamllint disable-line
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: "{{ docker_repo_url }}/ubuntu/gpg"

# Dotfiles
# --------
# Bash
dotfiles_bash_repo: git@github.com:marcus-grant/dots-bash
