# host_vars/thor.yml
---
# Author: Marcus Grant
# Description: Host variables for Thor workstation (Framework Desktop, Ryzen AI Max+ 395)

# Git
# ---
git_extra_packages: [lazygit]

zsh_extra_packages: [starship, bat, curl, fd, fzf, ripgrep, atuin, wl-clipboard]
