---
- name: Create Traefik directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ admin_user }}"
    group: docker
    mode: 0770
  loop:
    - "{{ traefik_data_directory }}"
    - "{{ traefik_data_directory }}/letsencrypt"

- name: Template Traefik config.toml
  ansible.builtin.template:
    src: traefik.toml
    dest: "{{ traefik_data_directory }}/traefik.toml"
    mode: 0770
    owner: "{{ admin_user }}"
    group: docker
  register: template_config

# DELETEME
# - name: Debug traefik_acme_email
#   ansible.builtin.debug:
#     msg: "{{ traefik_acme_email }}"

- name: Traefik Docker Container
  community.docker.docker_container:
    name: traefik
    image: "{{ traefik_docker_image }}"
    pull: true
    network_mode: host
    volumes:
      - "{{ traefik_data_directory }}/traefik.toml:/etc/traefik/traefik.toml:ro"
      - "{{ traefik_data_directory }}/letsencrypt:/letsencrypt:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    env: "{{ traefik_environment_variables }}"
    restart_policy: unless-stopped
    recreate: "{{ template_config is changed }}"
    # memory: "{{ traefik_memory }}"
