---
# - name: Ensure homebrew taps are in place
#   community.general.homebrew_tap:
#     name: "{{ item }}"
#     state: present
#   loop: "{{ homebrew_taps }}"

- name: Ensure homebrew packages are installed
  community.general.homebrew:
    name: "{{ hombrew_pkgs_pkg }}"
    state: present
    path: /opt/homebrew/bin
  loop_control: {loop_var: hombrew_pkgs_pkg}
  loop: "{{ homebrew_installed_packages }}"

- name: Ensure homebrew CASKS are installed
  community.general.homebrew_cask:
    name: "{{ hombrew_pkgs_cask }}"
    state: present
    path: /opt/homebrew/bin  # TODO same as the other todo
  loop_control: {loop_var: hombrew_pkgs_cask}
  loop: "{{ homebrew_installed_casks }}"

# TODO: Move to own role
- name: Ensure MAS client installed
  community.general.homebrew:
    name: mas
    state: present
    path: /opt/homebrew/bin
  when: mas_installed_apps | length > 0 or mas_uninstalled_apps | length > 0

- name: Install App Store apps in mas_installed_apps using MAS
  community.general.mas:
    id: "{{ hombrew_pkgs_mas_app.id | default(0) | int }}"
    state: present
  loop_control: {loop_var: hombrew_pkgs_mas_app}
  loop: "{{ mas_installed_apps }}"
  when: hombrew_pkgs_mas_app.id is defined and hombrew_pkgs_mas_app.id | int > 0
  tags: [skip_ansible_lint]

- name: UNInstall App Store apps in mas_installed_apps using MAS
  community.general.mas:
    id: "{{ hombrew_pkgs_mas_app_uninstall.id | default(0) | int }}"
    state: present
  loop_control: {loop_var: hombrew_pkgs_mas_app_uninstall}
  loop: "{{ mas_uninstalled_apps }}"
  when:
    - hombrew_pkgs_mas_app_uninstall.id is defined
    - hombrew_pkgs_mas_app_uninstall.id | int > 0
  tags: [skip_ansible_lint]
