---
- name: Converge
  hosts: all
  tasks:
    - name: Include bash role
      include_role:
        name: bash
      vars:
        bash_set_default_shell: true
        bash_dotfiles_repo: 'https://github.com/marcus-grant/dots-bash'
        bash_dotfiles_dest: ~/.config/bash
        bash_dotfiles_git_force: true
