---
- name: Converge
  hosts: all
  tasks:
    - name: Include bash role
      include_role:
        name: bash
      vars:
        bash_set_default_shell: true
        bash_dotfiles_repo: 'https://github.com/marcus-grant/dots-bash'
        bash_dotfiles_dest: "{{ ansible_env.HOME }}/.config/bash"
        bash_dotfiles_git_force: true
        bash_dotfiles_bashrc: "{{ bash_dotfiles_dest }}/rc.bash"
        bash_dotfiles_profile: "{{ bash_dotfiles_dest }}/profile.bash"
        bash_dotfiles_backup: true
