---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Get the current git remote origin of bash_dotfile_dir
    shell: 'cd ~/.config/bash && git remote -v'
    register: bash_shell_git_remote

  - name: print bash_shell_git_remote
    debug:
      msg: '{{ bash_shell_git_remote.stdout }}'

  - name: Register dotfile repo gitignore to check for forced checkout
    shell: cat ~/.config/bash/.gitignore
    register: gitignore

  - name: Assert prepare play string not in gitignore, assuring force checkout works 
    assert:
      that: "'ANSIBLE FAILI SHOULDNT BE HERE!' not in gitignore.stdout"


  # - name: Assert that git remote has an SSH based URI
  #   assert:
  #     that: "'git@github.com' in bash_shell_git_remote"
