---
# tasks file for roles/postgres
# - name: Install PostgreSQL
#   ansible.builtin.package:
#     name: "{{ postgres_pkg }}"
#     state: present
#   loop_control: {loop_var: postgres_pkg}
#   loop: "{{ psql_pkgs[ansible_os_family] | default(psql_pkgs.default) }}"
#   notify: Apply postgres service

- name: Find postgres main directory
  ansible.builtin.find:
    paths: /etc/postgresql
    file_type: directory
    recurse: false
  register: psql_find

- name: Set fact for postgres main directory by checking latest version dir
  ansible.builtin.set_fact:
    postgres_main_config_dir: >-
      {{ psql_find.files | selectattr('path') |
      map(attribute='path') | list | first }}/main
  when: psql_find.files | length > 0

- name: Ensure listen address is set to all (*)
  ansible.builtin.lineinfile:
    path: "{{ postgres_main_config_dir }}/postgresql.conf"
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
    state: present
  notify: Apply postgres service

# TODO: configure hba properly

- name: Copy over from playbook the permissive pg_hba.conf
  ansible.builtin.copy:
    src: pg_hba.conf.unsafe
    dest: "{{ postgres_main_config_dir }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: 0644
  notify: Apply postgres service
  when: postgres_permissive_hba

- name: Add postgres superuser with password on host machine
  ansible.builtin.user:
    name: postgres
    password: "{{ postgres_superuser_password | password_hash('sha512') }}"
    update_password: always
