---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 10000
      when: ansible_facts['os_family'] == "Debian"
    - name: Ensure git is installed, needed for cloning
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
    - name: Ensure ~/.config exists
      file:
        path: ~/.config
        state: directory
        mode: umask
    - name: Ensure pre-existing tmux config files exist to test replacing them
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: umask
      loop:
        - { path: ~/.tmux.conf, state: touch }
        - { path: ~/.tmux, state: directory }
        - { path: ~/.tmux/i_should_not_exist.txt, state: touch }
    - name: Clone an older commit of tmux dotfiles repo to test git.force
      git:
        repo: https://github.com/marcus-grant/dots-tmux
        dest: ~/.config/tmux
        version: 7b438d78ae35f92dab3c2caf51e7d9c682fb02d8
