---
# Prepare play to prepare docker containers,
# used to bring instance to testable state.
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt cache on Debian family OSs
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Ensure git is isntalled, expected by role
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - curl

    - name: Ensure ~/.config exists
      ansible.builtin.file:
        path: ~/.config
        state: directory
        mode: umask

    - name: Add pre-existing zshrc config file to test overriding/backups
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: umask
      loop:
        - { path: ~/.zshrc, state: touch }
        - { path: ~/.zsh, state: directory }
        - { path: ~/.zsh/helloworld.txt, state: touch }
    
    - name: Clone older commit of zsh dotfiles to test git force/backup
      ansible.builtin.git:
        repo: https://github.com/marcus-grant/dots-zsh
        dest: ~/.config/zsh
        version: 9a08747e30058d966fbcb9bbe5c3929892272da1
