---
# main tasks file for docker_config role
- name: Ensure default docker-compose directory exists
  ansible.builtin.file:
    path: /etc/docker/compose
    state: directory
    mode: '0755'
    owner: root
    group: docker
    recurse: true

- name: Add users to docker group
  become: true
  become_user: root
  ansible.builtin.user:
    name: "{{ docker_config_user }}"
    groups: docker
    append: true
  loop_control: {loop_var: docker_config_user}
  loop: "{{ docker_config_group_users }}"
  when: docker_config_group_users | length > 0

