---
fail2ban_enabled: true
fail2ban_service_default_state: started
fail2ban_conf_dir: /etc/fail2ban
fail2ban_global_jail_file: "{{ fail2ban_conf_dir }}/jail.local"

fail2ban_ignoreips: ['127.0.0.1/8', '::1']
fail2ban_bantime_maxtime: 43200  # 12 hours
fail2ban_bantime: 900
fail2ban_maxretry: 5
fail2ban_findtime: 900

# (OLD) - defaults file
# DELETEME - If the old version of this role is no longer used, delete this and
# in the meanwhile just use these comments as guidelines if needed
# use old tasks
fail2ban_old_tasks: false
