---
# Dotfiles
# --------

### Git / Gitea
git_default_branch: main  # [main]
git_user_name: Marcus Grant
git_user_email: marcusfg@protonmail.com
git_pull_rebase: false  # [false]
# git_gh_enabled: true  # [false]
# git_ssh_enabled: true  # [false]
# git_gh_token: "{{ vault_git_gh_token }}"

### Bash
dotfiles_bash_repo: git@github.com:marcus-grant/dots-bash
bash_set_default_shell: false
dotfiles_bash_git_force: false

### Vim
vim_git_repo: git@github.com:marcus-grant/dots-vim

### TMux
tmux_git_repo: git@github.com:marcus-grant/dots-tmux

### Pacman Packages
pacman_extra_packages:
  - flatpak
  - git
  - gnome-software
  - htop
  - iotop
  - lazygit
  - ncdu
  - pandoc
  - ranger
  - snapper
  - snap-pac
  - tldr
  - tree
  - wl-clipboard
  - xclip

###### GUI
### Flatpak
flatpak_install_gnome_software: true
flatpak_user_flatpaks:
  - org.freecadweb.FreeCAD
  - org.mozilla.firefox
  - com.discordapp.Discord
  - com.mojang.Minecraft
  - org.libretro.RetroArch
  - com.spotify.Client
  - com.usebottles.bottles
  - org.chromium.Chromium
  - com.github.liferooter.textpieces
# flatpak_system_flatpaks:
#   - com.spotify.Client
#   - com.usebottles.bottles
#   - org.chromium.Chromium
#   - com.github.liferooter.textpieces

