---
# User
# ----
admin_user_group: admin

### SSH
ssh_exclude_hosts: [loki, jord]
ssh_exclude_groups: [mac, hetzner]
ssh_custom_keys:
  - {
      name: git.key,
      comment: "git@{{ inventory_hostname }}",
      pass: "{{ admin_main_git_password }}",
    }
ssh_git_key: "{{ ssh_custom_keys[0].name }}"
ssh_config_custom_entries:
  - {
      name: jord,
      url: "{{ valhalla_main_domain }}",
      user: root,
      port: "{{ ssh_main_port }}",
    }
  - {
      name: github.com,
      url: github.com,
      user: git,
      key: "{{ ssh_git_key }}",
      agent: true,
    }
  - { name: codeberg.org, user: git, key: "{{ ssh_git_key }}", agent: true }
  - { name: gitlab.com, user: git, key: "{{ ssh_git_key }}" }
  - {
      name: git.marcusgrant.me,
      port: 48513,
      user: git,
      key: "{{ ssh_git_key }}",
      agent: true,
    }
ssh_manual_transfers:
  - { pub: "{{ ssh_git_key }}", location: https://github.com/settings/keys }
  - {
      pub: "{{ ssh_git_key }}",
      location: https://codeberg.org/user/settings/keys,
    }
  - { pub: id_ed25519, location: "{{ hostvars['brokkr']['ansible_host'] }}" }
  - { pub: id_ed25519, location: "{{ hostvars['freyja']['ansible_host'] }}" }
  - {
      pub: id_ed25519,
      location: https://console.hetzner.cloud/projects/1125228/security/sshkeys,
    }

### Git / Gitea
git_default_branch: main # [main]
git_user_name: Marcus Grant
git_user_email: "{{ admin_email_alt }}"
git_pull_rebase: false # [false]

### Profile
profile_group: "{{ admin_user_group }}"
profile_xdg_include: true # DELETEME: No longer necessary with userdirs role
profile_ls_colors: cxexfxdxBxEhebAbAgAcAd
profile_d_path: ~/.config/profile.d
profile_editor: nvim
profile_envs:
  - { name: CARGO_HOME, value: $XDG_DATA_HOME/cargo }
  - { name: PNPM_HOME, value: $XDG_DATA_HOME/pnpm }
  # - {name: PYENV_ROOT, value: $XDG_DATA_HOME/pyenv}  # DELETEME: Moved to pyenv role
profile_custom_entries:
  - "{{ '#' }} Secrets"
  - "export EMAIL='{{ admin_email }}'"
  # - 'eval "$(pyenv init -)"'  # DELETEME: if this works with pyenv role, remove

### Bash
dotfiles_bash_repo: git@github.com:marcus-grant/dots-bash
bash_set_default_shell: false
dotfiles_bash_git_force: false

### Vim
vim_git_repo: git@github.com:marcus-grant/dots-vim

### NeoVim
neovim_git_repo: git@github.com:marcus-grant/lazyvim.git
neovim_pkgs_extra: [fzf, ripgrep, fd, tree-sitter]
neovim_install_method: package # The default method, here for reminder

### TMux
tmux_git_repo: git@github.com:marcus-grant/dots-tmux

### ZSH
zsh_git_repo: git@github.com:marcus-grant/dots-zsh.git
zsh_rc_file: rc.zsh
zsh_profile_file: profile.zsh
zsh_env_file: env.zsh

# Dev
# ---
# PyEnv
pyenv_root: "$HOME/.local/share/pyenv"
pyenv_versions: ["3.7.3", "3.11.2", "3.12.0"]
pyenv_version_global: "3.11.2"
pyenv_profile_d_path: "{{ profile_d_path }}"

# pip
pip_sys_extra: [pip-completion, pip-tools]
pip_packages_common: [python-dotenv, numpy, pandas, matplotlib, seaborn]
pip_packages_global: [jupyter]

### Pacman Packages
pacman_extra_packages:
  - flatpak
  - git
  - gnome-software
  - htop
  - iotop
  - lazygit
  - ncdu
  - pandoc
  - ranger
  - snapper
  - snap-pac
  - tldr
  - tree
  - wl-clipboard
  - xclip

###### GUI
### Flatpak
flatpak_install_gnome_software: true
flatpak_user_flatpaks:
  - org.freecadweb.FreeCAD
  - org.mozilla.firefox
  - com.discordapp.Discord
  - com.mojang.Minecraft
  - org.libretro.RetroArch
  - com.spotify.Client
  - com.usebottles.bottles
  - org.chromium.Chromium
  - com.github.liferooter.textpieces
# flatpak_system_flatpaks:
#   - com.spotify.Client
#   - com.usebottles.bottles
#   - org.chromium.Chromium
#   - com.github.liferooter.textpieces
