---
# main tasks file for marcus_grant.dotfiles.neovim
# TODO - SET THE EDITOR VAR WHEN PROFILE ROLE SUPPORTS profile.d loading
- name: Install neovim packages + extras via package manager
  ansible.builtin.package:
    name: "{{ neovim_packages }}"
    state: present
  loop_control: {loop_var: neovim_packages}
  loop: "{{ ['neovim'] + neovim_pkgs_extra }}"

- name: Ensure neovim config directory (PARENT) exists
  ansible.builtin.file:
    path: "{{ neovim_config_dir | dirname }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0750

- name: Register stat of neovim config directory's git sub-directory
  ansible.builtin.stat:
    path: "{{ neovim_config_dir }}/.git"
  register: neovim_git_dir
  when:
    - neovim_git_repo is defined
    - neovim_git_repo | length > 0

- name: Clone neovim dotfiles repository to neovim config directory
  ansible.builtin.git:
    repo: "{{ neovim_git_repo }}"
    version: "{{ neovim_git_vers }}"
    force: "{{ neovim_git_force }}"
    dest: "{{ neovim_config_dir }}"
  when:
    - neovim_git_repo is defined
    - neovim_git_repo | length > 0
    - not neovim_git_dir.stat.exists or neovim_git_force
